projects:
  RestaurantAPI:
    schemaPath: src\graphql\schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src\graphql
        graphQLApiId: 3ymxj2yiwnemhf4b72hy3sdqzu
      endpoints:
        prod: >-
          https://akjqkyc2yfe6vmuk4u5pcrkzji.appsync-api.ap-south-1.amazonaws.com/graphql
